sudo: required
language: python

addons:
  apt:
    packages:
      - unzip
      # Java8 Required for Sonar and SQLCL
      - oracle-java8-installer
      - oracle-java8-set-default
  sonarqube:
    token:
      secure: ${SONAR_TOKEN}
    branches:
      - develop
      - master

services:
  - docker

env:
  global:
    - UT3_OWNER=ut3
    - UT3_OWNER_PASSWORD=ut3
    - UT3_USER=ut3_user
    - UT3_USER_PASSWORD=ut3
    - UT3_TABLESPACE=users
    # Target Branch and Directory for Deployment of Docs
    - PAGES_TARGET_BRANCH="gh-pages"
    - PAGES_VERSION_BASE="version3"
    - CACHE_DIR=$HOME/.cache
    # Database Env
    - SQLCLI="$HOME/sqlcl/bin/sql"
    - ORACLE_PWD="oracle"
  matrix:
    - ORACLE_VERSION="12c-se-r1" CONNECTION_STR='127.0.0.1:1521/ORCLPDB1'
    - ORACLE_VERSION="11g-xe-r2" CONNECTION_STR='127.0.0.1:1521/XE'        DOCKER_OPTIONS='--shm-size=1g'
    - ORACLE_VERSION="12c-se2-r2-v2" CONNECTION_STR='127.0.0.1:1521/ORCLPDB1'

cache:
  pip: true
  directories:
    - $CACHE_DIR
    - node_modules

install:
  - pip install mkdocs
  - bash .travis/install_sqlcl.sh
  - bash .travis/start_db.sh

script:
  - bash .travis/install.sh
  - bash .travis/run_examples_and_tests.sh
#  - bash .travis/run_test_as_user.sh
#  - bash .travis/build_docs.sh
#  - bash .travis/push_docs_to_gh_pages.sh
  - sonar-scanner
  - bash .travis/coveralls_uploader.sh

deploy:
  provider: releases
  api_key: $github_api_token
  file:
     - utPLSQL$TRAVIS_TAG.zip
     - utPLSQL$TRAVIS_TAG.tar.gz
  skip_cleanup: true
  on:
     repo: utPLSQL/utPLSQL
     tags: true

notifications:
  slack: utplsql:oiMuXO95TvKeAUENuDt4cPrB
